name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - uses: psf/black@stable
      with:
        src: "./src"

  deploy:
    name: Deploy
    needs: lint
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 5

    if: contains(github.ref, 'main')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Deploy
      run: |
        make ci_deploy
